import type { NextPage } from 'next'
import Head from 'next/head'
import * as S from '../styles/home'
import { ArrowRight } from '../assets/icons/ArrowRight'

const Home: NextPage = () => {
  return (
    <S.Container>
      <Head>
        <title>Collection-Willingly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <S.AplicationHome>
        <S.Question>
          <S.Title>
            Por que <a>Ajudar</a> o mundo ?
          </S.Title>
        </S.Question>
        <S.RedirectPage>
          <S.Ball/>
          <S.Ball/>
          <S.Ball/>
          <S.Icon onClick={() => {alert('deubom')}}>
            <ArrowRight width={50} height={50} />
          </S.Icon>
        </S.RedirectPage>
      </S.AplicationHome>
    </S.Container>
  )
}

export default Home
